AWSTemplateFormatVersion: '2010-09-09'
Description: A stack that creates the resources required to complete the Amazon API Gateway WebSocket tutorial.

Parameters:
  StageName:
    Type: String
    Default: production

Resources:
  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  ConnectHandlerServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  ConnectHandlerServiceRoleDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
              - dynamodb:DescribeTable
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - ConnectionsTable
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: ConnectHandlerServiceRoleDefaultPolicy
      Roles:
        - Ref: ConnectHandlerServiceRole
  ConnectHandler:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |-
          import json
          import logging
          import os
          import boto3
          from botocore.exceptions import ClientError

          logger = logging.getLogger()
          logger.setLevel("INFO")

          ddb_client = boto3.client('dynamodb')

          def lambda_handler(event, context):
              try:
                  params = event.get('queryStringParameters') or {}
                  if params.get('type') == "cli" and params.get('cliId'):
                      ddb_client.put_item(
                          TableName=os.environ['TABLE_NAME'],
                          Item={
                              'id': {'S': params['cliId']},
                              'connectionId': {'S': event['requestContext']['connectionId']}
                          }
                      )
                      logger.info("Stored: %s", json.dumps(params))
                  if params.get('type') == "mpc" and params.get('mpcId'):
                      ddb_client.put_item(
                          TableName=os.environ['TABLE_NAME'],
                          Item={
                              'id': {'S': params['mpcId']},
                              'connectionId': {'S': event['requestContext']['connectionId']}
                          }
                      )
                      logger.info("Stored: %s", json.dumps(params))
                  return {'statusCode': 200}
              except Exception as e:
                  logger.error("Failed to store connection ID: %s", e)
                  return {'statusCode': 500}
      Role:
        Fn::GetAtt:
          - ConnectHandlerServiceRole
          - Arn
      Environment:
        Variables:
          TABLE_NAME:
            Ref: ConnectionsTable
      Handler: index.lambda_handler
      Timeout: 5
      Runtime: python3.12
    DependsOn:
      - ConnectHandlerServiceRoleDefaultPolicy
      - ConnectHandlerServiceRole
  DisconnectHandlerServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  DisconnectHandlerServiceRoleDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
              - dynamodb:DescribeTable
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - ConnectionsTable
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: DisconnectHandlerServiceRoleDefaultPolicy
      Roles:
        - Ref: DisconnectHandlerServiceRole
  DisconnectHandler:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |-
          import json
          import logging
          import os
          import boto3
          from botocore.exceptions import ClientError

          logger = logging.getLogger()
          logger.setLevel("INFO")

          ddb_client = boto3.client('dynamodb')

          def lambda_handler(event, context):
              try:
                  item = {
                      'connectionId': {
                          'S': event['requestContext']['connectionId']
                      }
                  }
                  
                  delete_item(
                      table_name=os.environ['TABLE_NAME'],
                      item=item
                  )
              except Exception as e:
                  logger.error("Something went wrong with deleting the item from the table! Here's what: %s", e)
                  return {
                      'statusCode': 500
                  }
              
              return {
                  'statusCode': 200
              }

          def delete_item(table_name, item):
              try:
                  ddb_client.delete_item(
                      TableName=table_name,
                      Key=item
                  )
                  logger.info(
                      "Connection ID removed from table: %s",
                      json.dumps(item)
                  )
              except ClientError as err:
                  logger.error(
                      "Couldn't delete item %s from table %s. Here's why: %s: %s",
                      json.dumps(item),
                      table_name,
                      err.response["Error"]["Code"],
                      err.response["Error"]["Message"],
                  )
                  raise
      Role:
        Fn::GetAtt:
          - DisconnectHandlerServiceRole
          - Arn
      Environment:
        Variables:
          TABLE_NAME:
            Ref: ConnectionsTable
      Handler: index.lambda_handler
      Runtime: python3.12
    DependsOn:
      - DisconnectHandlerServiceRoleDefaultPolicy
      - DisconnectHandlerServiceRole
  GetConnectionIdHandlerServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  GetConnectionIdHandler:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |-
          import boto3
          import json
          import logging

          logger = logging.getLogger()
          logger.setLevel("INFO")

          def lambda_handler(event, context):
              logger.info("Received event: %s", json.dumps(event))
              try:
                  connection_id = event["requestContext"]["connectionId"]
                  domain = event["requestContext"]["domainName"]
                  stage = event["requestContext"]["stage"]

                  endpoint_url = f"https://{domain}/{stage}"
                  client = boto3.client("apigatewaymanagementapi", endpoint_url=endpoint_url)

                  response_body = {"connectionId": connection_id}

                  client.post_to_connection(
                      ConnectionId=connection_id,
                      Data=json.dumps(response_body).encode("utf-8")
                  )

                  return {"statusCode": 200, "body": "Connection ID sent"}
              except Exception as e:
                  logger.error("Failed to send connection ID: %s", e)
                  return {"statusCode": 500, "body": json.dumps({"error": str(e)})}
      Role: !GetAtt GetConnectionIdHandlerServiceRole.Arn
      Handler: index.lambda_handler
      Runtime: python3.12
  manageConnections:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: execute-api:ManageConnections
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:execute-api:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - ":"
                  - "*/*/POST/@connections/*"
        Version: "2012-10-17"
      PolicyName: manageConnections7F91357B
      Roles:
        - Ref: GetConnectionIdHandlerServiceRole
        - Ref: SendServerHandlerServiceRole
  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: WebSocketApi
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"
  WebSocketApiDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - ConnectRoute
      - DisconnectRoute
    Properties:
      ApiId: !Ref WebSocketApi
  WebSocketApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: !Ref StageName
      DeploymentId: !Ref WebSocketApiDeployment
      ApiId: !Ref WebSocketApi
  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConnectHandler.Arn}/invocations
      IntegrationMethod: POST
  DisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DisconnectHandler.Arn}/invocations
      IntegrationMethod: POST
  MockIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: MOCK
  GetConnectionIdIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetConnectionIdHandler.Arn}/invocations
      IntegrationMethod: POST
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: "$connect"
      AuthorizationType: NONE
      Target: !Sub integrations/${ConnectIntegration}
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: "$disconnect"
      AuthorizationType: NONE
      Target: !Sub integrations/${DisconnectIntegration}
  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: "$default"
      AuthorizationType: NONE
      Target: !Sub integrations/${MockIntegration}
  GetConnectionIdRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: "getConnectionId"
      AuthorizationType: NONE
      Target: !Sub integrations/${GetConnectionIdIntegration}
  ConnectLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt ConnectHandler.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*/$connect
  DisconnectLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt DisconnectHandler.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*/$disconnect
  GetConnectionIdPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt GetConnectionIdHandler.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*/getConnectionId
  SendServerHandlerServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  SendServerHandlerServiceRoleDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:DescribeTable
            Resource:
              - Fn::GetAtt:
                  - ConnectionsTable
                  - Arn
      PolicyName: SendServerHandlerServiceRolePolicy
      Roles:
        - Ref: SendServerHandlerServiceRole
  SendServerHandler:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |-
          import boto3
          import json
          import os
          import logging

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          ddb = boto3.client("dynamodb")

          def lambda_handler(event, context):
              try:
                  logger.info("Received event: %s", json.dumps(event))
                  body = json.loads(event.get("body", '{}'))

                  id = body.get("targetId")
                  operation_type = body.get("operationType")
                  msg = body.get("message")

                  if not id or not operation_type:
                      return {"statusCode": 400, "body": json.dumps({"error": "Missing Id or operationType"})}

                  # Get connectionId by Id
                  response = ddb.get_item(
                      TableName=os.environ['TABLE_NAME'],
                      Key={'id': {'S': id}}
                  )

                  if 'Item' not in response:
                      return {"statusCode": 404, "body": json.dumps({"error": "Id not found"})}

                  connection_id = response['Item']['connectionId']['S']

                  domain = event["requestContext"]["domainName"]
                  stage = event["requestContext"]["stage"]
                  endpoint_url = f"https://{domain}/{stage}"

                  client = boto3.client("apigatewaymanagementapi", endpoint_url=endpoint_url)

                  payload = {
                      "operationType": operation_type,
                      "peerConnectionId": event["requestContext"]["connectionId"],
                      "message": msg
                  }

                  client.post_to_connection(
                      ConnectionId=connection_id,
                      Data=json.dumps(payload).encode('utf-8')
                  )

                  return {"statusCode": 200, "body": "Message sent to CLI"}
              except Exception as e:
                  logger.error("Failed to send message to CLI: %s", e)
                  return {"statusCode": 500, "body": json.dumps({"error": str(e)})}
      Role: !GetAtt SendServerHandlerServiceRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref ConnectionsTable
      Handler: index.lambda_handler
      Runtime: python3.12
    DependsOn:
      - SendServerHandlerServiceRole
      - SendServerHandlerServiceRoleDefaultPolicy
  SendServerIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SendServerHandler.Arn}/invocations
      IntegrationMethod: POST
  SendServerRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: "sendServer"
      AuthorizationType: NONE
      Target: !Sub integrations/${SendServerIntegration}
  SendServerLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt SendServerHandler.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*/sendServer

Outputs:
  ConnectHandlerFunction:
    Description: Lambda function for the $connect route of the WebSocket API
    Value: !GetAtt 'ConnectHandler.Arn'
  DisconnectHandlerFunction:
    Description: Lambda function for the $disconnect route of the WebSocket API
    Value: !GetAtt 'DisconnectHandler.Arn'
  WebSocketApiId:
    Description: "ID of the WebSocket API"
    Value: !Ref WebSocketApi
  WebSocketApiEndpoint:
    Description: "WebSocket API endpoint"
    Value: !Sub "wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"